### PR TITLE
Fix AppVeyor downloading a corrupted Miniconda

### PR DESCRIPTION
**Pull request by hadim**
Should fix https://ci.appveyor.com/project/conda-forge/lapack-feedstock/build/1.0.24/job/cm6vb5fknxp5clo0 and all the others https://ci.appveyor.com/project/conda-forge/cython-feedstock/build/job/8d6tmrwj6twtwqal

### CODE REVIEW

**Comment by hadim** [comment]
@pelson @jakirkham

**Comment by bjodah** [comment]
+1, I ran into this here too:
https://github.com/conda-forge/sundials-feedstock/pull/3

**Comment by scopatz** [comment]
And I ran into this here: https://github.com/conda-forge/cyclus-feedstock/pull/7

**Comment by ocefpaf** [comment]
@hadim this is the right fix but we are trying to move away from Obvious-CI. (Also, only @pelson has merge rights here and I imagine he will quite busy for the next few weeks.)

Maybe we should move this functionality to `conda-smithy`? Do you want to try implementing this there?

**Comment by ocefpaf** [comment]
BTW I have been using the pre-installed AppVeyor's miniconda in all my projects. We should consider doing that again in conda-forge.

**Comment by scopatz** [comment]
@ocefpaf that would be ideal, having single points of failure is never a good idea - even if that point is the indefatigable @pelson :)

**Comment by scopatz** [comment]
And sorry I ran into a Mac issue on Travis, not this appveyor one.

**Comment by ocefpaf** [comment]
BTW I am adding this change here as a patch in the obvious-ci feedstock right now. So we can ponder on a proper solution later.

**Comment by ocefpaf** [comment]
> And sorry I ran into a Mac issue on Travis, not this appveyor one.

I am looking into that too... hold on.

**Comment by hadim** [comment]
Fix has been merged in conda-smithy.

**Comment by ocefpaf** [comment]
@hadim there some some people out there that still uses `obvious-ci`. So I would leave this open.

**Comment by bjlittle** [comment]
@pelson :+1: Merge please!

**Comment by jakirkham** [comment]
Friendly nudge @pelson . Hoping to unbury this one. 😉

**Comment by pelson** [comment]
Thanks @hadim (and all reviewers). From memory, we don't actually need a new release, right? The script is accessed directly from master - could somebody confirm this?

**Comment by ocefpaf** [comment]
> Thanks @hadim (and all reviewers). From memory, we don't actually need a new release, right? The script is accessed directly from master - could somebody confirm this?

No new release. As it is a bootstrap it is desirable to get it from `master` and not a versioned URL/release.

However, many are now getting this from `conda-smithy`. It would be nice if that can be a new home for it b/c more people have merge rights there and fixes can be merged quicker.

**Pull request merged**
