### PR TITLE
Remove the docker image

### PR DESCRIPTION
**Pull request by jakirkham**
Removing the docker image here as it is migrating to conda-forge as shown by this PR ( https://github.com/conda-forge/docker-images/pull/5 ). This came out of a [discussion]( https://github.com/conda-forge/conda-forge.github.io/pull/121/files#diff-e482962a4824eb0dcd693fea95aca49eR116 ) between @pelson and myself after the general meeting on the 2016-04-29.

### CODE REVIEW

**Comment by pelson** [comment]
Don't know what happens to dockerhub, but it will be interesting to see! 👍

**Comment by jakirkham** [comment]
It probably will complain it can't find the Dockerfile, but its easy enough to disable that.

**Comment by jakirkham** [comment]
FWIW I know there are no more feedstocks relying on this image. So, if you wanted to remove it, I think you should be safe on the conda-forge end.

**Comment by pelson** [comment]
https://github.com/SciTools/conda-recipes-scitools/blob/master/circle.yml#L9 😉

**Comment by jakirkham** [comment]
Hence the conda-forge end. 😜

**Pull request merged**
