### PR TITLE
Simplified the fix from #37.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by pelson** [comment]
This still isn't quite building correctly (though the build string is good). Need to dig a little deeper into conda-build again.

**Comment by pelson** [comment]
Ping @ocefpaf.

**Comment by pelson** [comment]
@ocefpaf - as it stands, we need to define ``numpy x.x`` in both run and build dependencies which have a numpy C dependency. Hopefully that will be simplified by https://github.com/conda/conda-build/pull/650.

**Comment by ocefpaf** [comment]
Thanks @pelson! I ended up implementing a [workaround](https://github.com/ioos/conda-recipes/pull/538/files), but I will make some tests tomorrow.

**Pull request merged**
