### PR TITLE
PY3: .iteritems() -> .items()

### PR DESCRIPTION
**Pull request by ericdill**
Could also do this with six, but I did not see it listed as a dependency of this project, so falling back to `items()` seems like the right approach

### CODE REVIEW

**Comment by pelson** [comment]
Thanks @ericdill. For what it's worth, this codebase is soon to be deprecated in favour of conda-build-all. There is improved testing and py3k improvements there. Would you mind also checking your fix is applicable there?

Thanks! https://github.com/SciTools/conda-build-all

**Comment by ericdill** [comment]
Sure thing.  Thanks for the manual deprecation warning :smile: 

I assume this means that you going to update `staged-recipes` to use conda build all instead of obvious-ci?

**Comment by pelson** [comment]
>  I assume this means that you going to update staged-recipes to use conda build all instead of obvious-ci?

That is pretty much the main thing stopping me from *actually* deprecating the ObviousCI build capability at this moment in time. It shouldn't be a big job, just need to get around to it :smile:

**Comment by ericdill** [comment]
Ah fair enough :smile: 

I've been making heavy use of staged-recipes for my own nefarious purposes at NSLS2 and can give  transitioning to `conda-build-all` a shot if that would be helpful.

There is no usage of `iteritems` in conda-build-all btw.

**Comment by pelson** [comment]
> There is no usage of iteritems in conda-build-all btw.

Great, thanks @ericdill. That was my hope - there is a *ton* more testing in conda-build-all, and it is CI tested against py2k + py3k, so I was hopeful. :wink: 

> [I] can give transitioning to conda-build-all a shot if that would be helpful.

That would be great! If you need any tips as you go, just shout (feel free to open an issue on staged-recipes). Just so you know, in my head staged-recipes uploading is heading the way of the dodo :bird:, and eventually it will have CI build but *without* the upload. Instead, upon merge, the recipe will *automatically* be turned into a feedstock, from whence it will be built and uploaded to conda-forge. I've not really talked to anybody about that intention, but wanted to give you a little background before you get stuck in.

> I've been making heavy use of staged-recipes for my own nefarious purposes at NSLS2

Really interested to hear more...
How will feedstocks impact that use?

**Comment by ericdill** [comment]
> Really interested to hear more...

I have recently gone remote and moved from Long Island (where Brookhaven is) back to Raleigh, NC (where I grew up) and so have lost easy access to the build system that we have been using at NSLS2.  Granted, this "build system" is just the hardware (one specific server that we were building all our conda packages on) and the person-hours required to manually build our stack. Manually building conda packages is not a sustainable pursuit, as I would imagine you already know since you're working on tooling to automate it.

Going remote has offered me physical distance (~600 miles) from the firefighting duties at NSLS2 and so I can spend time removing some of the pain points for our on-site devs (@danielballan, @tacaswell, among others).  One of these "dev-opsy" projects that I'm tackling is to get tagged versions of software in our stack automatically building.  Last week I stumbled upon `staged-recipes` and wanted to try to get our stack automatically building.  As I don't need windows/osx builds for our stack, I forked `conda-forged/staged-recipes` and have been mostly victorious fighting with it, conda-build, circle-ci and obvious-ci to get recipes building and uploading to https://anaconda.org/lightsource2.  There are about 10 more recipes I want to get working, but [here] (https://github.com/NSLS-II/staged-recipes) are most of them.  

I see that you just found nsls-ii/wishlist#96 with my other two dev-opsy projects for building conda-packages on travis and building docs on travis for most of the projects at NSLS-II. Thanks for pointing out pelson/package_with_continuous_delivery. I'll have a look.

I am also using staged-recipes to get tagged builds for the https://github.com/scikit-beam/scikit-beam project.

> How will feedstocks impact [the use mentioned above]?

For my use case, I am guessing that feedstocks on a per-recipe basis would be over kill since we have a very homogeneous deployment target both in terms of software and hardware as basically everything at NSLS2 is the same model of HP workstation or IBM server with Debian 7 or 8 installed.  As such, having staged-recipes automatically build and upload new/changed recipes upon push to master is a fantastic solution where the only pain point is just to get the right deps installed into the docker image.  Do I understand correctly that one reason for having a feedstock-per-recipe approach is to allow full customization of the build environment on a per-recipe basis?  Oh I see that there another huge benefit in that you get fine-grained control over who manages each feedstock.  What are some of the other advantages that you see in this approach? 

> Instead, upon merge, the recipe will automatically be turned into a feedstock, from whence it will be built and uploaded to conda-forge

Won't this be difficult since you need to fully configure each of the three CI platforms with the right set of credentials, including encrypting a BINSTAR_TOKEN?  Oh wait I see now. Since this is all on conda-forge, you already have access to these credentials and binstar token needed to upload to anaconda.org/conda-forge.  Wouldn't that mean that you would also need to grant `recipe-maintainers` access to the `conda-forge` channel on anaconda.org so that they could remove bad packages that were uploaded?

**Pull request merged**
