### PR TITLE
binstar -> conda-server

### PR DESCRIPTION
**Pull request by ocefpaf**
`conda-server` is the "new" `binstar` and `binstar_client`...

### CODE REVIEW

**Comment by pelson** [comment]
Weird windows problem:

```
binstar -t %BINSTAR_TOKEN% upload %FNAME% -u pelson -c development --force
usage: binstar-script.py [-h] [--show-traceback] [--hide-traceback] [-v] [-q]
                         [--color] [--no-color] [-V] [-t TOKEN] [-s SITE]
                         COMMAND ...
binstar-script.py: error: argument COMMAND: invalid choice: 'is' (choose from 'auth', u'channel', 'config', u'copy', 'groups', u'login', 'logout', u'notebook', 'package', 'remove', 'search', 'show', u'upload', u'whoami')
```

**Comment by ocefpaf** [comment]
I guess that the output of `conda build obvious-ci.conda --output > obvci_fname.txt` changed on Windows.  Trying to find a Windows machine here to test it...

**Comment by ocefpaf** [comment]
Nope.  The command `conda build obvious-ci.conda --output > obvci_fname.txt` still outputs the target name correctly.  I am clueless here...  :unamused:

**Comment by pelson** [comment]
> I am clueless here...

Yeah, me too. @malev, do you happen to have any insight?

**Comment by malev** [comment]
@pelson, the command seems ok. Could you try:
`conda remove binstar`
`conda install conda-server`
and try it again but with `conda server` instead of `binstar`?

**Comment by ocefpaf** [comment]
@malev I don't believe `binstar` is installed in the appveyor setup. Unless I am missing something...

(This PR purpose is to switch from `binstar` to `conda-server` in the `obvci_install_conda_build_tools.py`.)

**Comment by pelson** [comment]
Perhaps https://github.com/pelson/Obvious-CI/blob/master/appveyor.yml#L47 @ocefpaf?

**Comment by ocefpaf** [comment]
> Perhaps https://github.com/pelson/Obvious-CI/blob/master/appveyor.yml#L47 @ocefpaf?

That `binstar` call **is** from the new `conda-server` (and now I see that we can/should change it to `conda server`):

https://github.com/Anaconda-Server/conda-server/blob/develop/setup.py#L24

Unless the old `binstar` is being installed somewhere else that I am missing...

**Comment by ocefpaf** [comment]
I changed the call  from `binstar` to the new `conda server` (according to [this](https://github.com/Anaconda-Server/conda-server/blob/develop/setup.py#L24-25) they should be the same anyways) and the problem persists.

I believe that this might be a bug in `conda-server` for Windows.

**Comment by ocefpaf** [comment]
And it changed again...

See https://github.com/Anaconda-Server/anaconda-client/blob/develop/setup.py#L24-L25

**Comment by pelson** [comment]
I agree. @malev - I think there is a bug with the command line parsing on windows. I didn't take a deep look to track it down, but you can see the appveyor logs from this PR.

**Comment by malev** [comment]
@pelson would you mind reporting the issue in https://github.com/Anaconda-Server/anaconda-client

**Pull request merged**
